on: [push]

name: 'Build: GNU + Linux (ARM64)'

jobs:
  linux_aarch64:
    name: GNU + Linux (ARM64)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Install development dependencies
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install -qq libgtk-4-0 libgtk-4-dev libglib2.0-dev > /dev/null
          git clone https://gitlab.gnome.org/GNOME/glib.git && cd glib > /dev/null
          meson _build && ninja -C _build
          sudo ninja -C _build install
          ./build-dependencies.sh
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: aarch64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Build Oku
        uses: actions-rs/cargo@v1
        with:
          cross: true
          command: build
          args: --release --all-features --target aarch64-unknown-linux-gnu
      - name: Prepare Oku for upload
        run: |
          cd ./target/aarch64-unknown-linux-gnu/release/
          chmod +x ./oku
          tar -cvf aarch64-oku.gnu+linux.tar \
          oku
      - name: Upload Oku build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-oku.gnu+linux
          path: ./target/aarch64-unknown-linux-gnu/release/aarch64-oku.gnu+linux.tar
          if-no-files-found: error
