on: [push]

name: Evaluate codebase

jobs:
  code_check:
    name: Evaluate codebase
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Install development dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq gtk3.0 gtk2.0 libgtk-3-dev libgtk2.0-dev libglib2.0-dev glade libsoup-gnome2.4-dev libwebkit2gtk-4.0-dev > /dev/null
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          profile: minimal
      - name: Check codebase is properly formatted
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args:  -- --check
      - name: Check codebase using linter
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings