on: [push]

name: Code coverage

jobs:
  codecovio:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install development dependencies
        run: |
          sudo apt-get install -y gtk3.0 gtk2.0 libgtk-3-dev libgtk2.0-dev libglib2.0-dev glade libsoup-gnome2.4-dev libwebkit2gtk-4.0-dev

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--out Lcov'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.15
        with:
          token: ${{secrets.CODECOV_TOKEN}}
      
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './lcov.info'

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: cobertura.xml