on: [push]

name: 'Package: Debian GNU + Linux (x86_64)'

jobs:
  deb_x86-64:
    name: Debian GNU + Linux (x86_64)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Install development dependencies
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install -qq libgtk-4-0 libgtk-4-dev libglib2.0-dev > /dev/null
          git clone https://gitlab.gnome.org/GNOME/glib.git && cd glib > /dev/null
          meson _build && ninja -C _build
          sudo ninja -C _build install
          ./build-dependencies.sh
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Install 'cargo-deb'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb
      - name: Build & package Oku
        uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --separate-debug-symbols -- --all-features --target x86_64-unknown-linux-gnu
      - name: Upload Oku build artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-oku.deb.gnu+linux
          path: ./target/debian/oku_*_amd64.deb
          if-no-files-found: error