on:
  push:
    branches:    
        - master

name: Lint codebase

jobs:
  code_lint:
    name: Lint codebase
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install development dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq gtk3.0 gtk2.0 libgtk-3-dev libgtk2.0-dev libglib2.0-dev glade libsoup-gnome2.4-dev libwebkit2gtk-4.0-dev > /dev/null
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          profile: minimal
          components: clippy, rustfmt
      - name: Correct code files
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --fix -Z unstable-options
      - name: Commit changes to code, if any
        run: |
          git config --global user.name 'Oku'
          git config --global user.email 'Dirout@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || git commit -am "Automatically approved suggested code corrections by linter"
          git push