on: [push]

name: 'Build: macOS (x86_64)'

jobs:
  mac_x86-64:
    name: macOS (x86_64)
    runs-on: macos-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Install development dependencies
        run: |
          brew install gtk+3 libsoup libpsl
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          profile: minimal
      - name: Build Oku
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target x86_64-apple-darwin
      - name: Prepare Oku for upload
        run: |
          cd ./target/x86_64-apple-darwin/release/
          strip ./oku
          chmod +x ./oku
          tar -cvf x86_64-oku.osx.tar \
          oku
      - name: Upload Oku build artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-oku.osx
          path: ./target/x86_64-apple-darwin/release/x86_64-oku.osx.tar
          if-no-files-found: error