on:
  release:
    types: [published]

name: 'Publish: crates.io'

jobs:
  publish:
    name: 'Publish: crates.io'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          #components: rust-src, clippy, rustfmt
      - name: Login to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: login
          args:  ${{ secrets.CRATES_LOGIN }}
      - name: Package Oku
        uses: actions-rs/cargo@v1
        with:
          command: package
      - name: Publish Oku
        uses: actions-rs/cargo@v1
        with:
          command: publish